import {ui,exercises,baseline,sources,warmup} from './content.js';
import {pace,wordCount,recommend} from './core.js';
import {Microphone} from './microphone.js';
const KEY='clear-speech-studio:v1';
const defaults=()=>({version:1,lang:'de',focus:'pace',level:1,goal:3,context:0,target:120,history:[]});
let state=defaults(),storageOK=true;
try{const raw=JSON.parse(localStorage.getItem(KEY)); if(raw?.version===1){
 state={...state,lang:['de','en'].includes(raw.lang)?raw.lang:'de',focus:['pace','clarity','syllables'].includes(raw.focus)?raw.focus:'pace',level:[1,2,3].includes(raw.level)?raw.level:1,goal:[1,3,5].includes(raw.goal)?raw.goal:3,context:[0,1,2].includes(raw.context)?raw.context:0,target:Number.isFinite(raw.target)&&raw.target>=30&&raw.target<=300?raw.target:120,history:Array.isArray(raw.history)?raw.history.filter(x=>x && ['de','en'].includes(x.lang)&&Number.isFinite(x.seconds)&&typeof x.date==='string'&&Number.isFinite(x.rating)&&Number.isFinite(x.effort)).slice(-2000):[]};
}}catch{storageOK=false;}
let view='practice',step=0,variant=0,isBaseline=false,active=false,startTime=0,ticker,seconds=0,mic=null,audioURL=null,requestID=0,completed=false;
const $=s=>document.querySelector(s);
const t=()=>ui[state.lang];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const day=()=>new Date().toLocaleDateString('en-CA');
const localDay=d=>new Date(d).toLocaleDateString('en-CA');
const persist=()=>{try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch{storageOK=false;notice(t().storage);}};
const notice=s=>{const n=$('#notice');if(n)n.textContent=s;};
const records=()=>state.history.filter(x=>x.lang===state.lang);
function current(){
 if(isBaseline)return {id:'comparison-v1',title:t().baseline,instruction:t().baselineHint,text:baseline[state.lang],level:0};
 if(step===0){const e=warmup[state.lang];return {id:'warmup',title:e[0],instruction:e[1],text:e[2],level:0};}
 const index=(state.level-1)*2+(step===1?variant%2:(variant+1)%2);
 const e=exercises[state.lang][state.focus][index];
 return {id:`${state.focus}-${index}`,title:e[0],instruction:e[1],text:e[2],level:Math.floor(index/2)+1};
}
function clearAudio(){if(audioURL){URL.revokeObjectURL(audioURL);audioURL=null;}}
function cleanup(){requestID++;stop(false);clearAudio();seconds=0;completed=false;}
function shell(){const u=t();document.documentElement.lang=state.lang;document.title=`Clear Speech Studio · ${state.lang==='de'?'Klar sprechen':'Speak clearly'}`;
 $('#app').innerHTML=`<a class="skip" href="#main">${u.skip}</a><header class="topbar"><div class="brand"><img src="./icon.svg" alt="" width="38" height="38">Clear Speech Studio</div><nav class="mainnav" aria-label="${state.lang==='de'?'Hauptnavigation':'Main navigation'}">${['practice','progress','guide'].map(v=>`<button data-view="${v}" ${v===view?'aria-current="page"':''}>${u[v]}</button>`).join('')}</nav><div class="languages"><button data-lang="de" lang="de" aria-pressed="${state.lang==='de'}">Deutsch</button><button data-lang="en" lang="en" aria-pressed="${state.lang==='en'}">English</button></div></header><div id="notice" role="status" aria-live="polite" class="notice"></div><main id="main" class="wrap" tabindex="-1"></main>`;
 if(view==='practice')renderPractice();else if(view==='progress')renderProgress();else renderGuide();
 $('#main').insertAdjacentHTML('beforeend',`<footer class="footer"><span>Clear Speech Studio · ${u.resetHint}</span><a href="https://github.com/rwiermerstudio/clear-speech-studio">${state.lang==='de'?'Quellcode & Dokumentation':'Source & documentation'} ↗</a></footer>`);
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{cleanup();view=b.dataset.view;shell();$('#main').focus();});
 document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{if(state.lang===b.dataset.lang)return;cleanup();state.lang=b.dataset.lang;persist();shell();});
 if(!storageOK)notice(u.storage);
}
function options(values,chosen){return values.map(([v,label])=>`<option value="${v}" ${String(v)===String(chosen)?'selected':''}>${esc(label)}</option>`).join('');}
function renderPractice(){const u=t(),e=current(),today=records().filter(x=>localDay(x.date)===day()&&x.kind==='practice').length;
 $('#main').innerHTML=`<div class="heading"><div><p class="eyebrow">${u.tag}</p><h1>${u.headline}</h1><p>${u.intro}</p></div><span class="privacy-pill">${state.lang==='de'?'Lokal. Privat. Ohne Konto.':'Local. Private. No account.'}</span></div>
 <details id="settings"><summary>${u.settings}</summary><form id="preferences"><div class="fields"><label class="field">${u.focus}<select id="focus">${options(Object.entries(u.focusNames),state.focus)}</select></label><label class="field">${u.level}<select id="level">${options(u.levels.map((x,i)=>[i+1,`${i+1} · ${x}`]),state.level)}</select></label><label class="field">${u.goal}<select id="goal">${options([1,3,5].map(x=>[x,x]),state.goal)}</select></label><label class="field">${u.context}<select id="context">${options(u.contexts.map((x,i)=>[i,x]),state.context)}</select></label><label class="field full">${u.target}<input id="target" type="number" min="30" max="300" value="${state.target}"><span class="hint">${u.targetHint}</span></label></div><div class="actions"><button class="primary" type="submit">${u.apply}</button></div><p class="hint">${u.rules}</p></form></details>
 <div class="layout"><aside class="rail"><p class="eyebrow">${u.personal}</p><h2>${u.today}</h2><p class="hint">${u.planHint}</p><div class="plan-list">${[0,1,2].map((n)=>{const index=n===0?0:(state.level-1)*2+(n===2?1:0);return `<button data-step="${n}" ${!isBaseline&&step===n?'aria-current="step"':''}><span class="number">0${n+1}</span><span><strong>${esc(n===0?warmup[state.lang][0]:exercises[state.lang][state.focus][index][0])}</strong><small>${u.step} ${n+1} · ${u.levels[n===0?0:state.level-1]}</small></span></button>`;}).join('')}</div><button class="secondary" id="baseline">${u.baseline} ↗</button><div class="goal-line">${u.daily}<strong>${today} / ${state.goal}</strong><progress max="${state.goal}" value="${Math.min(today,state.goal)}" aria-label="${u.daily}"></progress><p class="hint">${today>=state.goal?u.done:u.focusNames[state.focus]}</p></div><p class="hint">${u.recommend}: ${recommend(state.history,state.lang,state.focus,state.level)} · ${u.levels[recommend(state.history,state.lang,state.focus,state.level)-1]}</p></aside>
 <div><section class="studio" aria-labelledby="exercise-title"><div class="studio-top"><span class="chip">${isBaseline?(records().some(x=>x.kind==='baseline')?u.retestKind:u.baselineKind):`${u.levels[Math.max(0,e.level-1)]} · ${u.step} ${step+1}/3`}</span><button id="variant" ${isBaseline||step===0?'hidden':''}>${u.variant} ↻</button></div><div class="studio-body"><h2 id="exercise-title" class="exercise-title">${esc(e.title)}</h2><p class="instruction">${esc(e.instruction)}</p><div class="speaking" aria-label="${u.sample}">${esc(e.text).replaceAll(' / ',' <span class="slash" aria-hidden="true">/</span> ')}</div>
 ${isBaseline?`<p class="hint">${u.newBaseline}</p>`:''}<div class="coach"><strong>${u.coach}</strong><p id="cue">${u.cue[0]}</p></div><div class="timerbar"><output class="clock" id="clock" aria-label="${u.duration}">0:00</output><button id="start" class="primary">${u.start}</button><button id="mic">${u.mic}</button><button id="stop" hidden>${u.stop}</button></div><p class="hint">${u.manual}</p><details><summary>${u.privacyTitle}</summary><p class="hint">${u.micHint}</p></details>
 <div class="audio-panel" id="audio-panel" hidden><div class="meter-row"><label for="meter">${u.meter}</label><meter id="meter" min="0" max="1" value="0"></meter><span>${u.pauseLabel}: <strong id="pauses">0</strong></span></div><p id="feedback" role="status" aria-live="polite"></p><p class="hint">${u.measurement}</p></div><div id="playback-wrap" hidden><h3>${u.playback}</h3><audio id="playback" controls></audio><a id="audio-download" download="clear-speech-recording.webm">${u.downloadAudio}</a><p class="hint">${u.audioGone}</p></div>
 <form id="reflection" class="reflection"><h3>${u.listenTitle}</h3><p class="hint">${u.listen}</p><div class="fields"><label class="field">${u.seconds}<input id="seconds" type="number" min="3" max="1200" step="0.1" required inputmode="decimal"><span class="hint">${u.manual}</span></label><label class="field">${u.words}<input id="words" type="number" min="1" max="5000" step="1" inputmode="numeric"><span class="hint">${u.noWords}</span></label><div class="full"><button id="count" type="button">${u.count}</button><p class="hint">${u.countHint}</p></div><label class="field">${u.rating}<select id="rating" required><option value="">${u.choose}</option>${options(u.ratings.map((x,i)=>[i+1,`${i+1} · ${x}`]),'')}</select></label><label class="field">${u.effort}<select id="effort" required><option value="">${u.choose}</option>${options(u.efforts.map((x,i)=>[i+1,`${i+1} · ${x}`]),'')}</select></label><label class="field full">${u.notes}<textarea id="notes" maxlength="500" placeholder="${u.notesHint}"></textarea></label></div><div class="actions"><button class="primary" id="save" type="submit">${u.save}</button><button id="next" type="button">${u.next} →</button><output class="readout" id="pace">${u.noPace}</output></div><p class="hint">${u.paceExplain}</p></form></div></section><div class="support"><div><h3>${u.transfer}</h3><p>${u.transferHints[state.context]}</p></div><div><h3>${u.safetyTitle}</h3><p>${state.lang==='de'?'Bequem statt mit Kraft. Bei Schmerz oder Anstrengung stoppen. Plötzliche Sprachveränderung? Sofort Notruf (112).':'Comfort, not force. Stop for pain or strain. Sudden speech change? Call emergency services now.'}</p><button data-view="guide">${u.guide} ↗</button></div></div></div></div>`;
 $('#preferences').onsubmit=ev=>{ev.preventDefault();cleanup();state.focus=$('#focus').value;state.level=Number($('#level').value);state.goal=Number($('#goal').value);state.context=Number($('#context').value);state.target=Number($('#target').value);step=0;variant=0;isBaseline=false;persist();shell();};
 document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{cleanup();step=Number(b.dataset.step);variant=0;isBaseline=false;shell();});
 $('#variant').onclick=()=>{cleanup();variant++;shell();};$('#baseline').onclick=()=>{cleanup();isBaseline=true;shell();};
 $('#next').onclick=()=>{cleanup();isBaseline=false;step=(step+1)%3;variant=0;shell();$('#exercise-title').tabIndex=-1;$('#exercise-title').focus();};
 $('#start').onclick=()=>begin(false);$('#mic').onclick=()=>begin(true);$('#stop').onclick=()=>stop();
 $('#count').onclick=()=>{$('#words').value=wordCount(e.text.replaceAll('·',''));updatePace();notice(u.countNotice);};
 $('#words').oninput=updatePace;$('#seconds').oninput=updatePace;
 $('#effort').onchange=()=>{if(Number($('#effort').value)>=3)notice(u.strain);};
 $('#reflection').onsubmit=save;
}
function updatePace(){const p=pace(Number($('#words')?.value),Number($('#seconds')?.value));if($('#pace'))$('#pace').innerHTML=p===null?t().noPace:`${t().paceLabel}<br><strong>${p}</strong> ${t().wpm} <span class="hint">· ${state.target} ${state.lang==='de'?'Orientierung':'reference'}</span>`;}
function timerStart(){$('#mic').disabled=false;active=true;completed=false;startTime=performance.now();seconds=0;$('#start').hidden=true;$('#mic').hidden=true;$('#stop').hidden=false;$('#save').disabled=true;$('#seconds').disabled=true;$('#cue').textContent=t().cue[0];ticker=setInterval(()=>{seconds=(performance.now()-startTime)/1000;$('#clock').textContent=`${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;$('#cue').textContent=t().cue[Math.floor(seconds/12)%t().cue.length];if(seconds>=120){stop();notice(t().timeLimit);}},100);}
async function begin(withMic){if(active)return;clearAudio();$('#playback-wrap').hidden=true;$('#audio-panel').hidden=true;const id=++requestID;
 if(!withMic){timerStart();notice(t().running);return;}
 $('#mic').disabled=true;
 const engine=new Microphone(({rms,state:signal,pauses})=>{if(id!==requestID||!active)return;$('#meter').value=Math.min(1,rms*4);$('#pauses').textContent=pauses;const label=t()[signal];if($('#feedback').textContent!==label)$('#feedback').textContent=label;},blob=>{if(id!==requestID||!blob?.size)return;clearAudio();audioURL=URL.createObjectURL(blob);if($('#playback')){$('#playback').src=audioURL;$('#audio-download').href=audioURL;$('#audio-download').download=`clear-speech-recording.${blob.type.includes('mp4')?'mp4':'webm'}`;$('#playback-wrap').hidden=false;}});
 try{await engine.start();if(id!==requestID){engine.stop();return;}mic=engine;timerStart();$('#audio-panel').hidden=false;notice(engine.recording?t().listening:t().noAudio);}catch{engine.stop();if(id===requestID)notice(t().denied);}finally{if(id===requestID&&$('#mic'))$('#mic').disabled=false;}
}
function stop(update=true){if(active){seconds=(performance.now()-startTime)/1000;active=false;}clearInterval(ticker);if(mic){mic.stop();mic=null;}if(update&&$('#stop')){$('#start').hidden=false;$('#mic').hidden=false;$('#stop').hidden=true;$('#seconds').disabled=false;$('#seconds').value=seconds.toFixed(1);$('#save').disabled=false;$('#meter').value=0;$('#feedback').textContent=t().ready;updatePace();notice(t().ready);}}
function save(ev){ev.preventDefault();if(active||completed)return;const u=t(),s=Number($('#seconds').value),w=$('#words').value===''?null:Number($('#words').value),r=Number($('#rating').value),eff=Number($('#effort').value);if(!Number.isFinite(s)||s<3||s>1200||r<1||r>5||eff<1||eff>5){notice(u.tooShort);return;}
 const e=current(),kind=isBaseline?(records().some(x=>x.kind==='baseline')?'retest':'baseline'):'practice';
 state.history.push({date:new Date().toISOString(),lang:state.lang,focus:state.focus,level:e.level,exerciseId:e.id,kind,seconds:s,words:w,pace:pace(w,s),wordMethod:w===null?'none':'manual-confirmed',rating:r,effort:eff,notes:$('#notes').value.trim()});
 state.history=state.history.slice(-2000);persist();completed=true;$('#save').disabled=true;notice(`${u.saved}${eff>=3?' '+u.strain:''}${!storageOK?' '+u.storage:''}`);
 const today=records().filter(x=>localDay(x.date)===day()&&x.kind==='practice').length;$('.goal-line strong').textContent=`${today} / ${state.goal}`;$('.goal-line progress').value=Math.min(today,state.goal);$('.goal-line .hint').textContent=today>=state.goal?u.done:u.focusNames[state.focus];
}
function renderProgress(){const u=t(),h=records(),days=new Set(h.map(x=>localDay(x.date))).size,base=h.find(x=>x.kind==='baseline'),retest=h.filter(x=>x.kind==='retest').at(-1),mean=h.length?(h.reduce((a,x)=>a+x.rating,0)/h.length).toFixed(1):'—';
 $('#main').innerHTML=`<div class="heading"><div><p class="eyebrow">${u.progress} · ${state.lang==='de'?'Deutsch':'English'}</p><h1>${u.historyTitle}</h1><p>${u.historyIntro}</p></div></div><div class="stats"><div class="stat"><strong>${h.length}</strong><span>${u.attempts}</span></div><div class="stat"><strong>${days}</strong><span>${u.days}</span></div><div class="stat"><strong>${mean}</strong><span>${u.avg} / 5</span></div></div><h2>${u.compare}</h2><p class="hint">${u.compareHint}</p>${base&&retest?`<div class="comparison">${[base,retest].map((x,i)=>`<article><h3>${i?u.retestKind:u.baselineKind}</h3><p class="hint">${esc(new Date(x.date).toLocaleString(state.lang))}</p><p class="compare-metric">${x.pace??'—'} ${u.wpm}</p><p>${x.seconds} s · ${u.self}: ${x.rating}/5</p><p class="hint">${u.effort}: ${x.effort}/5</p></article>`).join('')}</div>`:`<p class="banner">${u.noCompare}</p>`}<p class="hint">${u.paceExplain}</p><h2>${u.milestone}</h2><div class="badges">${u.badges.map((b,i)=>{const earned=[h.length>0,days>=3,new Set(h.filter(x=>x.kind==='practice').map(x=>x.focus)).size===3][i];return `<div class="badge">${earned?'✓':'○'} ${b}<small>${earned?u.earned:u.locked}</small></div>`;}).join('')}</div><details><summary>${u.recommend}: ${recommend(state.history,state.lang,state.focus,state.level)}</summary><p>${u.rules}</p></details>${h.length?'':`<p class="banner">${u.empty}</p>`}<div class="table-wrap" tabindex="0" role="region" aria-label="${u.history}"><table id="history"><caption>${u.history}</caption><thead><tr><th scope="col">${u.date}</th><th scope="col">${u.exercise}</th><th scope="col">${u.duration}</th><th scope="col">${u.wpm}</th><th scope="col">${u.self}</th><th scope="col">${u.effort}</th></tr></thead><tbody>${h.slice(-50).reverse().map(x=>`<tr><td>${esc(new Date(x.date).toLocaleDateString(state.lang))}</td><td>${esc(x.kind==='practice'?exerciseName(x):x.kind==='baseline'?u.baselineKind:u.retestKind)}</td><td>${x.seconds} s</td><td>${x.pace??'—'}</td><td>${x.rating}/5</td><td>${x.effort}/5</td></tr>`).join('')}</tbody></table></div><div class="actions"><button id="export">${u.export}</button><button class="danger" id="erase">${u.erase}</button></div>`;
 $('#export').onclick=()=>download(JSON.stringify({...state,exportedAt:new Date().toISOString(),metricDefinitions:{pace:'manual words / full seconds including pauses * 60',rating:'self-rated understandability 1–5',effort:'self-rated effort 1–5'}},null,2),'application/json','clear-speech-progress.json');
 $('#erase').onclick=()=>{if(!confirm(u.confirm))return;cleanup();const lang=state.lang;state=defaults();state.lang=lang;try{localStorage.removeItem(KEY);}catch{storageOK=false;}shell();notice(u.deleted);};
}
function exerciseName(x){if(x.exerciseId==='warmup')return warmup[state.lang][0];const parts=String(x.exerciseId).split('-');return exercises[state.lang]?.[parts[0]]?.[Number(parts[1])]?.[0]||t().practiceKind;}
function download(data,type,name){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function renderGuide(){const u=t();$('#main').innerHTML=`<div class="guide"><p class="eyebrow">${u.guide}</p><h1>${u.methodTitle}</h1><p>${u.methodIntro}</p><section class="safety"><h2>${u.safetyTitle}</h2><p>${u.safety}</p></section><section><h2>${u.sourceTitle}</h2><ol>${sources.map(([title,url],i)=>`<li><p>${u.sources[i]}</p><a href="${url}" rel="noreferrer" target="_blank">${title} ↗</a></li>`).join('')}</ol><p class="hint">${state.lang==='de'?'Originale Übungstexte. Keine Verbindung zu oder Empfehlung durch ASHA/NHS. Quellen geprüft: 9. September 2026. Quellen auf Englisch.':'Original practice material. Not affiliated with or endorsed by ASHA/NHS. Sources checked: September 9, 2026. Sources in English.'}</p></section><section><h2>${u.limitsTitle}</h2><p>${u.limits}</p><p>${u.paceExplain}</p></section><section><h2>${u.privacyTitle}</h2><p>${u.privacy}</p></section><section><h2>${u.listenTitle}</h2><p>${u.listen}</p><p>${u.rules}</p></section></div>`;}
window.addEventListener('pagehide',()=>cleanup());
document.addEventListener('visibilitychange',()=>{if(document.hidden){requestID++;stop();}});
shell();
